sudo: required
language: python

services:
- docker

python:
  - "2.7"
  - "3.5"

addons:
  apt:
    update: true
    
before_script:
  - sudo apt-get install -y python3-gevent python-gevent
  - chmod 777 ./pyArango/tests/setup_arangodb.sh
  - ./pyArango/tests/setup_arangodb.sh
  - apt-g
  - pip install coverage

install: python setup.py install

script: coverage run -m unittest discover pyArango/tests/

after_success: bash <(curl -s https://codecov.io/bash)
