sudo: required
language: python

services:
- docker

python:
  - "2.7"
  - "3.5"

before_script:
  - chmod 777 ./pyArango/tests/setup_arangodb.sh
  - ./pyArango/tests/setup_arangodb.sh
  - pip install coverage

install: python setup.py install

script: coverage run -m unittest discover pyArango/tests/

after_success: bash <(curl -s https://codecov.io/bash)
