sudo: required
language: python

services:
- docker

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    update: true
    
before_script:
  - pip install coverage gevent enum setuptools
  - chmod 777 ./pyArango/tests/setup_arangodb.sh
  - ./pyArango/tests/setup_arangodb.sh

install:
  - pip install --upgrade --user pip
  - python setup.py install

script: coverage run -m unittest discover pyArango/tests/

after_success: bash <(curl -s https://codecov.io/bash)
